### PR TITLE
WIP: ppc64 cleanup

### PR DESCRIPTION
**Pull request by hramrach**

### CODE REVIEW

**Comment by SchoolGuy** [comment]
@hramrach Would it be possible that you elaborate a bit what the target of the PR is please? The CI is not running because apparently you don't have the config files for the GH Actions in your branch, also it is weird that you are directly using the master branch instead of a feature branch. If you desire help, I will gladly assist but this PR is not yet at a point where I feel comfortable giving the green checkmark in the review.

**Comment by hramrach** [comment]
The goal is to make ppc64 bootable in Orthos.

ppc64le is bootable but ppc64 is not and there are differences in handling the two architectures.

If there are some CI config files missing on my branch it is because they are missing in your repository. I did not remove any.

**Comment by SchoolGuy** [comment]
Ahhh you opened this against the openSUSE Version. Please close this PR here and open it here: https://github.com/cobbler/cobbler

This `master` branch was not updated in a very long time and is not even close up to date.

**Comment by SchoolGuy** [comment]
I now synced the `master` branch with upstream and you will possibly see now why I was initially so confused...

**Pull request closed without merging**
