### PR TITLE
Add EFI chainloader for SLE-Micro

### PR DESCRIPTION
**Pull request by beninidavide**
Backport of https://github.com/cobbler/cobbler/pull/3675  

Add support of SLE-Micro to the chainload file

### CODE REVIEW

**Comment by m-czernek** [comment]
Thank you @beninidavide for the PR - as per [1], in addition to this PR, can you also please provide PRs for these branches?

- [uyuni/master](https://github.com/openSUSE/cobbler/tree/uyuni/master)
- [uyuni/stable](https://github.com/openSUSE/cobbler/tree/uyuni/stable)
- [suma/4.3](https://github.com/openSUSE/cobbler/tree/suma/4.3)

I will then accept the PR in all branches at once and can take care of the OBS/IBS SRs.

[1] https://github.com/openSUSE/cobbler/wiki/Uyuni-and-SUSE-Manager#conventions

**Comment by beninidavide** [comment]
Added PR for uyuni/master (https://github.com/openSUSE/cobbler/pull/91), uyuni/stable (https://github.com/openSUSE/cobbler/pull/92), suma/4.3 (https://github.com/openSUSE/cobbler/pull/93)

**Review by m-czernek — APPROVED** [review]

**Comment by m-czernek** [comment]
Perfect, TYVM!

**Comment by beninidavide** [comment]
Great, thank you @m-czernek for helping me with everything

**Pull request merged**
